<html>
	<head>
	<link href="services.css" rel="stylesheet">
		<title>
		</title>
	</head>
			<body>
			<div class="head">
					Services
					<div style="float:right">
						</div>
					</div>
					<div id="menu_bar">
					<a class="nav_link" href="mainpage.PHP">
					<div class="level_1">
					Home 
					</div>
				</a>
				<a class="nav_link" href="aboutus.PHP">
					<div class="level_1">
					About 
					</div>
				</a>
				<a class="nav_link" href="gallery.PHP">
					<div class="level_1">
					Gallery
					</div>
				</a>
				<a class="nav_link" href="services.PHP">
					<div class="level_1">
					Services
					</div>
				</a>
				<a class="nav_link" href="feedback.PHP">
					<div class="level_1">
					Feedback
					</div>
				</a>
				    </div>
						<div class="div_writtenarea">
							<div class="div_writtenarea_left">Our Services
							</div>
							<div class="div_writtenarea_right">Every photoshoot is unique with its planning and content which provides for exelent moments
							of imagery. Photos are provided in full resolution on data DVD disk for future usage and image slide show creation.
							<br><br>
							Reservation for photography services are required and a wide variety of great options available at the time of purchase. <br>
							We will be pleased to provide you a full photography services quote that is custom tailored to your requirement.
							After a detailed review, you can decide which options are best suited for your requirement.
							</div>
						</div>
					<div class="div_screen">
						<div class="div_screen_topleft">
							<div class="div_screen_topleft_up">
							<img src="editing.jpg">
							</div>
							<div class="div_screen_topleft_down">EDITING
							<br>Simple blemishes may be included in your package if retouching is quick and easy.
						</div>
					</div>
					<div class="div_screen_topcenter">
						<div class="div_screen_topcenter_up">
						<img src="sessions.jpg">
						</div>
						<div class="div_screen_topcenter_down_">
						SESSIONS<BR>
						Sessions can be booked and can vary in time length. Sessions usally include travelling.						
						</div>
					</div>
					<div class="div_screen_topright">
						<div class="div_screen_topright_up">
							<img src="events.jpg">
						</div>
							<div class="div_screen_topright_down_">
							EVENTS<BR>
							Sessions are welcomed and if out of state, travel time is included in the package.				
							</div>
					</div>
					
					</div>
					</div>
			</body>
</html>